/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as OportunidadesIndexRouteImport } from './routes/oportunidades.index'
import { Route as OportunidadesIdRouteImport } from './routes/oportunidades.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesIndexRoute = OportunidadesIndexRouteImport.update({
  id: '/oportunidades/',
  path: '/oportunidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesIdRoute = OportunidadesIdRouteImport.update({
  id: '/oportunidades/$id',
  path: '/oportunidades/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/planos': typeof PlanosRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/oportunidades/': typeof OportunidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/planos': typeof PlanosRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/oportunidades': typeof OportunidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/planos': typeof PlanosRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/oportunidades/': typeof OportunidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/planos' | '/oportunidades/$id' | '/oportunidades/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/planos' | '/oportunidades/$id' | '/oportunidades'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/planos'
    | '/oportunidades/$id'
    | '/oportunidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PlanosRoute: typeof PlanosRoute
  OportunidadesIdRoute: typeof OportunidadesIdRoute
  OportunidadesIndexRoute: typeof OportunidadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/': {
      id: '/oportunidades/'
      path: '/oportunidades'
      fullPath: '/oportunidades/'
      preLoaderRoute: typeof OportunidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/$id': {
      id: '/oportunidades/$id'
      path: '/oportunidades/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof OportunidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PlanosRoute: PlanosRoute,
  OportunidadesIdRoute: OportunidadesIdRoute,
  OportunidadesIndexRoute: OportunidadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
